sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker
install:
  - cd scripts && npm ci && cd ..

script:
  - node scripts/build
  - node scripts/test

deploy:
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy Production
    on:
      branch: master

env:
  # DEPLOY_SETTINGS_JSON='{"Production":[
  #   {"type":"docker","options":{"source":"chatbot-hepir","target":"zevere/chatbot-hepir","user":"","pass":""}},
  #   {"type":"heroku","options":{"app":"zv-chatbot-hepir","source":"zevere/chatbot-hepir","dyno":"web","user":"","token":""}}
  # ]}'
  - secure: CsolFH1aiK/yrkSwXzpk0IgRmZf3rpd9nyxqKU5qUL7PD059gkjnd3GszKy13t8OwqdxUi0p05wbSwITpHCUPgeDRNyUiEgTVx1DtlGDMS38AHz5ZesrCv9Xdxv0/P25XFRf4qS6np/2LeGbooBhEhhiue2A5CaZ0NZl4VhSRckhxCLwdEcQYJkxYyaLDouiroQhzPShEbP/ZpgA93FPLl1xrvwLwnMPm6OhpmFVSfKE2VmDK/dCmvaxU+VTNpVa+tYU+eaq5gMv6Xb1Spf9+vsVw9Uc0p7mEWm2+1oidykVDkmxOcaSdbmRei6AdemIHEJCPmWutMWy+zudD8I/bOWT8yBA4r2pLVROj/W9y5uTVH6htYMcqiVIq8coXALtQvn+dzzddKJdqVyqHSqNPjEkI6/cbfOUak9fa8fx3PNXWsP7uhHWDaYN54oUIPIYtamcXJjDs91DhPOMOCMaIp1MB2LzFqPhf7bxI5ZuMLiFgc9vGhfH6gY00XvfxSnHzkCr1/z02LiS4aGGRNIX69HTJ8tX5vAPWvAxyNrIFfPc+LNOIsPuoxKzmo+VwCToEohI5oG/yj9qaasgTqWcuRl6tQuzJmDRhrdCnPvLg5Nq7lBRnSNzkUg64FwzT1VAY6+dNrYjmUtnYZFQ2EJNNMej3ROqPhRqUILzcDXhdmQ=


# Disable "Build pushed pull requests"
