VALID_ZEVERE_USER = 'kevin.ma'
INVALID_ZEVERE_USER = 'fakename324'

VALID_TG_ID = '289934826'
INVALID_TG_ID = '123456789'

VALID_ZV_CONNECTION = VALID_ZEVERE_USER, VALID_TG_ID
INVALID_ZV_CONNECTION = INVALID_ZEVERE_USER, INVALID_TG_ID

LIST_TITLE = "Centennial College School Work"
LIST_DESCRIPTION = "This task list is for managing all the school work I have to do from class."

VALID_LIST_ID = LIST_TITLE.strip().lower().replace(' ', '_')
INVALID_LIST_ID = 'xxx. chalbye choo foo?'

VALID_LIST_AND_OWNER = VALID_ZEVERE_USER, VALID_LIST_ID
INVALID_OWNER_VALID_LIST = INVALID_ZEVERE_USER, VALID_LIST_ID
INVALID_OWNER_AND_LIST = VALID_ZEVERE_USER, INVALID_LIST_ID
